server:
  port: 8092

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mmall?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: x5219438

# 控制台输出日志
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl